// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmGTKlatVpIX_gj9kryCYGYD59yHbUoc0',
    appId: '1:806722239170:web:40842bb17242d06308d95b',
    messagingSenderId: '806722239170',
    projectId: 'mascotas-ce80e',
    authDomain: 'mascotas-ce80e.firebaseapp.com',
    storageBucket: 'mascotas-ce80e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwM32CvqOywEF6F1k_McZ0Q_laDCXqlRQ',
    appId: '1:806722239170:android:50982ff26185a6c108d95b',
    messagingSenderId: '806722239170',
    projectId: 'mascotas-ce80e',
    storageBucket: 'mascotas-ce80e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvu1uUpW9pGhZBGOoAq6NvWqlRS6in0g0',
    appId: '1:806722239170:ios:78f548da317a9d0308d95b',
    messagingSenderId: '806722239170',
    projectId: 'mascotas-ce80e',
    storageBucket: 'mascotas-ce80e.firebasestorage.app',
    iosBundleId: 'com.example.fireCrud5a25',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmGTKlatVpIX_gj9kryCYGYD59yHbUoc0',
    appId: '1:806722239170:web:566190faf45a617a08d95b',
    messagingSenderId: '806722239170',
    projectId: 'mascotas-ce80e',
    authDomain: 'mascotas-ce80e.firebaseapp.com',
    storageBucket: 'mascotas-ce80e.firebasestorage.app',
  );
}
